spring.application.name=Square game Demo
debug=true
randomheartbeat.id=42


game.defaultName = TicTacToe

game.GameCatalog.defaultName=TicTacToe
game.GameCatalog.defaultplayerCount=1
game.GameCatalog.defaultBoardSize=3

game.taquinPlugin.defaultplayerCount=1
game.taquinPlugin.defaultBoardSize=3

game.ticTacToePlugin.defaultplayerCount=2
game.ticTacToePlugin.defaultBoardSize=3

game.fourGamePlugin.defaultplayerCount=2
game.fourGamePlugin.defaultBoardSize=7